### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ljwango** [gluster/distaf#25]
Distaf is a distributed testing framework, but it can be done? What are the advantages? Whether can describe for me? I saw a test tool blockade yesterday, I know it can be done? But I see the distaf, I don't know what can it do?

**Comment by msvbhat** [comment]
Perhaps this will be of help. http://redhat.slides.com/msvbhat/deck-2-3#/

But then I will update the README soon and try to make a screestcast for better understanding.

Hope it helps.

**Comment by msvbhat** [comment]
I have now updated the README. Closing this issue
