### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by ljwango** [gluster/distaf#26]
I have two questions need to inquiry: 
1, when I perform the test case, prompt yaml is not found, yaml is what? How is generated? 
2, util.py document, testcase, test_list, test_seq, test_mount, globl_configs, global_mode, tc value fill out there is no limit? Can you see you how to fill in?

**Comment by msvbhat** [comment]
Hi,

Thanks for taking interest. I'm not sure I understand your question.  But I will try and answer from what I have understood.

1. yaml is a data specification format (https://en.wikipedia.org/wiki/YAML) similar to XML or JSON. In the case of distaf we specify the test machines through the yaml format. In the config.yaml file you specify the servers and clients that you want to run your tests with. Note that you should have the passwordless ssh setup between the management node (the node from which you start your tests) and the test machines.

2. You don't have to fill out any of these lists and/or dicts. They will be populated from the data that you specify in the yaml config file.

For more detail, please go through the presentation (http://redhat.slides.com/msvbhat/deck-2-3#/)

But note that the changes that went in recently were all gluster specific and are more suited to gluster usecase and less to other projects maybe. But there I have tagged it with a label which makes it pretty generic for other usecases as well.

Hope it helps.

**Comment by msvbhat** [comment]
Hope your question is answered. Closing the issue now.
